// Generated by CoffeeScript 1.6.3
(function() {
  var _ref, _ref1,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.TronEvent = (function(_super) {
    __extends(TronEvent, _super);

    function TronEvent() {
      _ref = TronEvent.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    return TronEvent;

  })(Backbone.Model);

  window.MinimalEventListEntryView = (function(_super) {
    __extends(MinimalEventListEntryView, _super);

    function MinimalEventListEntryView() {
      _ref1 = MinimalEventListEntryView.__super__.constructor.apply(this, arguments);
      return _ref1;
    }

    MinimalEventListEntryView.prototype.tagName = "tr";

    MinimalEventListEntryView.prototype.template = _.template("<td><%= dateFromNow(time) %></td>\n<td>\n  <span class=\"label <%= level %>\">\n    <%= name %>\n  </span>\n</td>");

    MinimalEventListEntryView.prototype.render = function() {
      this.$el.html(this.template(this.model.attributes));
      makeTooltips(this.$el);
      return this;
    };

    return MinimalEventListEntryView;

  })(Backbone.View);

}).call(this);
