// Generated by CoffeeScript 1.7.1
(function() {
  var NodeInlineView, NodeModel, NodePoolInlineView, NodePoolModel,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  NodeModel = (function(_super) {
    __extends(NodeModel, _super);

    function NodeModel() {
      return NodeModel.__super__.constructor.apply(this, arguments);
    }

    return NodeModel;

  })(Backbone.Model);

  NodePoolModel = (function(_super) {
    __extends(NodePoolModel, _super);

    function NodePoolModel() {
      return NodePoolModel.__super__.constructor.apply(this, arguments);
    }

    return NodePoolModel;

  })(Backbone.Model);

  NodeInlineView = (function(_super) {
    __extends(NodeInlineView, _super);

    function NodeInlineView() {
      this.render = __bind(this.render, this);
      return NodeInlineView.__super__.constructor.apply(this, arguments);
    }

    NodeInlineView.prototype.tagName = "span";

    NodeInlineView.prototype.template = _.template("<span class=\"tt-enable\" title=\"<%= username %>@<%= hostname %>:<%= port %>\">\n    <%= name %>\n</span>");

    NodeInlineView.prototype.render = function() {
      this.$el.html(this.template(this.model.attributes));
      return this;
    };

    return NodeInlineView;

  })(Backbone.View);

  NodePoolInlineView = (function(_super) {
    __extends(NodePoolInlineView, _super);

    function NodePoolInlineView() {
      this.render = __bind(this.render, this);
      return NodePoolInlineView.__super__.constructor.apply(this, arguments);
    }

    NodePoolInlineView.prototype.tagName = "span";

    NodePoolInlineView.prototype.template = _.template("<span class=\"tt-enable\" title=\"<%= nodes.length %> node(s)\">\n    <%= name %>\n</span>");

    NodePoolInlineView.prototype.render = function() {
      this.$el.html(this.template(this.model.attributes));
      return this;
    };

    return NodePoolInlineView;

  })(Backbone.View);

  window.displayNode = function(node) {
    return new NodeInlineView({
      model: new NodeModel(node)
    }).render().$el.html();
  };

  window.displayNodePool = function(pool) {
    return new NodePoolInlineView({
      model: new NodePoolModel(pool)
    }).render().$el.html();
  };

}).call(this);
